### ISSUE TITLE
meta state documentation

### ISSUE THREAD

**Issue by franksl** [websanova/vue-upload#20]
Hi,
I upgraded from a previous version and noticed that the 'sending' state (which was status) has been replaced with 'uploading'.
This change has not been updated in the documentation.
Thanks,
Frank

**Comment by websanova** [comment]
Thx for reporting all the issues.

I was a bit hasty releasing this as I needed the updates for a project.

I've updated the docs and tried to add some change log notes. There have been quite  few changes. I recommend re-reading the docs. It should be simpler overall now.

I screwed up the versioning as well with this, which is gonna add to the confusion here. Anyway, I've updated it to `v1.0.0-beta` now. I'll just leave it at that moving forward.

I guess there are actually some people using this plugin now, so will pay better attention with things moving forward. Otherwise it's quite a big overhaul and don't forsee too many changes coming any time soon. It's a lot more standardized and modern format.

Sorry for the confusion, let me know if you have any more issues / concerns / questions.

Thx :-)
